### ISSUE TITLE
model_generator crash when the config.yaml is empty.

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-model-generator#111]
```
Unhandled exception:
NoSuchMethodError: The method ‘forEach’ was called on null.
Receiver: null
Tried calling: forEach(Closure: (dynamic, dynamic) => Null)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      new YmlGeneratorConfig (package:model_generator/config/yml_generator_config.dart:30:29)
#2      main (file:///Users/user123/.pub-cache/hosted/pub.dartlang.org/model_generator-5.8.1/bin/model_generator.dart:51:7)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
```

**Comment by vanlooverenkoen** [comment]
A better error warning should be shown.

**Comment by NicolaVerbeeck** [comment]
Or nothing should happen (catch crash and continue silently)

**Comment by vanlooverenkoen** [comment]
Indeed that is what should be done
